import type { AutomationOverview } from "@/lib/outreach-automation";

export function createEmptyAutomationOverview(): AutomationOverview {
  return {
    settings: {
      id: "global",
      enabled: true,
      globalPaused: false,
      emailSystemPrompt: null,
      sendWindowStartHour: 9,
      sendWindowStartMinute: 0,
      sendWindowEndHour: 16,
      sendWindowEndMinute: 30,
      weekdaysOnly: true,
      initialDelayMinMinutes: 10,
      initialDelayMaxMinutes: 45,
      followUp1BusinessDays: 2,
      followUp2BusinessDays: 4,
      schedulerClaimBatch: 4,
      replySyncStaleMinutes: 15,
      createdAt: new Date(0),
      updatedAt: new Date(0),
    },
    ready: [],
    mailboxes: [],
    sequences: [],
    queued: [],
    active: [],
    finished: [],
    recentSent: [],
    recentRuns: [],
    engine: {
      mode: "ACTIVE",
      nextSendAt: null,
      scheduledToday: 0,
      blockedCount: 0,
      replyStoppedCount: 0,
      readyCount: 0,
      queuedCount: 0,
      waitingCount: 0,
      sendingCount: 0,
    },
    pipeline: {
      needsEnrichment: 0,
      enriching: 0,
      enriched: 0,
      readyForTouch: 0,
    },
    stats: {
      ready: 0,
      queued: 0,
      sending: 0,
      waiting: 0,
      blocked: 0,
      active: 0,
      paused: 0,
      stopped: 0,
      completed: 0,
      replied: 0,
      scheduledToday: 0,
    },
  };
}
