interface CloudflareEnv {
  APP_BASE_URL: string;
  AUTH_ALLOWED_EMAILS: string;
  AUTH_ADMIN_EMAILS: string;
  AUTH_ALLOWED_ORIGINS?: string;
  AGENT_SHARED_SECRET?: string;
  CLOUD_SCRAPE_ENABLED?: string;
  CLOUD_SCRAPE_TIMEOUT_MS?: string;
  CLOUD_SCRAPE_WORKER_NAME?: string;
  BETTER_AUTH_SECRET: string;
  GEMINI_API_KEY?: string;
  RATE_LIMIT_WINDOW_SECONDS: string;
  RATE_LIMIT_MAX_AUTH: string;
  RATE_LIMIT_MAX_SCRAPE: string;
  RATE_LIMIT_MAX_EXPORT: string;
  SCRAPE_CONCURRENCY_LIMIT: string;
  SCRAPE_TIMEOUT_MS: string;
  WORKER_HEARTBEAT_STALE_MS?: string;
  AUTONOMOUS_INTAKE_ENABLED?: string;
  AUTONOMOUS_QUEUE_ENABLED?: string;
  AUTONOMOUS_SEND_ENABLED?: string;
  AUTONOMOUS_DAILY_LEAD_INTAKE_CAP?: string;
  AUTONOMOUS_MAX_SENDS_PER_DAY?: string;
  AUTONOMOUS_DOMAIN_COOLDOWN_DAYS?: string;
}
